services:
  dk_bot:
    build:
      context: .
    volumes:
      - ./data:/app/data
      - ./log/archive:/app/log/archive
      - ./settings.py:/app/settings.py:ro
      - ./credentials.json:/app/credentials.json:ro